### PR TITLE
Add command line arguments for bash mode

### PR DESCRIPTION
**Pull request by er1c**
Also fixes being able to use `~/output.json` by using https://www.npmjs.com/package/untildify

### CODE REVIEW

**Comment by anhthang** [comment]
@er1c thank you for this PR. it's great if `commander` or `inquirer` can support both. Did you try?

**Comment by er1c** [comment]
@buianhthang I did look into it.  I can remove the prompting, but I thought it a nice feature.  Inquirer has a "this isn't for command line args: see commander"

`commander` has required parameters, but not console prompting beyond the var args

**Comment by er1c** [comment]
@buianhthang FYI, I'm playing with/adding additional swagger generation options: https://github.com/er1c/soap-converter/commit/81e6800c6abbc235a0a0012de157d3b3523e7751#diff-04c6e90faac2675aa89e2176d2eec7d8R30 do you want me to submit a PR when I get those ready?  (I'm purposefully trying to keep the PRs small/easy to review)

**Comment by anhthang** [comment]
@er1c I also think it’s nice feature. I just want to make sure that we don’t use multiple packages with the same features

New PRs are welcome. Thank you :D

**Pull request merged**
